/*
 * This file is generated by jOOQ.
 */
package app.biptrip.bipbackend.jooq;


import app.biptrip.bipbackend.jooq.tables.Users;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tables {

    /**
     * The table <code>public.users</code>.
     */
    public static final Users USERS = Users.USERS;
}
