/*
 * This file is generated by jOOQ.
 */
package app.biptrip.bipbackend.jooq.tables;


import app.biptrip.bipbackend.jooq.Keys;
import app.biptrip.bipbackend.jooq.Public;
import app.biptrip.bipbackend.jooq.tables.Events.EventsPath;
import app.biptrip.bipbackend.jooq.tables.Users.UsersPath;
import app.biptrip.bipbackend.jooq.tables.records.TicketsRecord;

import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tickets extends TableImpl<TicketsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.tickets</code>
     */
    public static final Tickets TICKETS = new Tickets();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TicketsRecord> getRecordType() {
        return TicketsRecord.class;
    }

    /**
     * The column <code>public.tickets.id</code>.
     */
    public final TableField<TicketsRecord, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.tickets.event_id</code>.
     */
    public final TableField<TicketsRecord, Integer> EVENT_ID = createField(DSL.name("event_id"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.tickets.user_id</code>.
     */
    public final TableField<TicketsRecord, Integer> USER_ID = createField(DSL.name("user_id"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.tickets.qr_url</code>.
     */
    public final TableField<TicketsRecord, String> QR_URL = createField(DSL.name("qr_url"), SQLDataType.VARCHAR(255), this, "");

    private Tickets(Name alias, Table<TicketsRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Tickets(Name alias, Table<TicketsRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.tickets</code> table reference
     */
    public Tickets(String alias) {
        this(DSL.name(alias), TICKETS);
    }

    /**
     * Create an aliased <code>public.tickets</code> table reference
     */
    public Tickets(Name alias) {
        this(alias, TICKETS);
    }

    /**
     * Create a <code>public.tickets</code> table reference
     */
    public Tickets() {
        this(DSL.name("tickets"), null);
    }

    public <O extends Record> Tickets(Table<O> path, ForeignKey<O, TicketsRecord> childPath, InverseForeignKey<O, TicketsRecord> parentPath) {
        super(path, childPath, parentPath, TICKETS);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class TicketsPath extends Tickets implements Path<TicketsRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> TicketsPath(Table<O> path, ForeignKey<O, TicketsRecord> childPath, InverseForeignKey<O, TicketsRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private TicketsPath(Name alias, Table<TicketsRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public TicketsPath as(String alias) {
            return new TicketsPath(DSL.name(alias), this);
        }

        @Override
        public TicketsPath as(Name alias) {
            return new TicketsPath(alias, this);
        }

        @Override
        public TicketsPath as(Table<?> alias) {
            return new TicketsPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public Identity<TicketsRecord, Integer> getIdentity() {
        return (Identity<TicketsRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<TicketsRecord> getPrimaryKey() {
        return Keys.TICKETS_PKEY;
    }

    @Override
    public List<ForeignKey<TicketsRecord, ?>> getReferences() {
        return Arrays.asList(Keys.TICKETS__FK_EVENT, Keys.TICKETS__FK_USER);
    }

    private transient EventsPath _events;

    /**
     * Get the implicit join path to the <code>public.events</code> table.
     */
    public EventsPath events() {
        if (_events == null)
            _events = new EventsPath(this, Keys.TICKETS__FK_EVENT, null);

        return _events;
    }

    private transient UsersPath _users;

    /**
     * Get the implicit join path to the <code>public.users</code> table.
     */
    public UsersPath users() {
        if (_users == null)
            _users = new UsersPath(this, Keys.TICKETS__FK_USER, null);

        return _users;
    }

    @Override
    public Tickets as(String alias) {
        return new Tickets(DSL.name(alias), this);
    }

    @Override
    public Tickets as(Name alias) {
        return new Tickets(alias, this);
    }

    @Override
    public Tickets as(Table<?> alias) {
        return new Tickets(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Tickets rename(String name) {
        return new Tickets(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Tickets rename(Name name) {
        return new Tickets(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Tickets rename(Table<?> name) {
        return new Tickets(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Tickets where(Condition condition) {
        return new Tickets(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Tickets where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Tickets where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Tickets where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Tickets where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Tickets where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Tickets where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Tickets where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Tickets whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Tickets whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
